// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bis-browse/Browse.tsx": () => import("../components/mockups/bis-browse/Browse.tsx"),
  "./components/mockups/bis-detail/Detail.tsx": () => import("../components/mockups/bis-detail/Detail.tsx"),
  "./components/mockups/bis-homepage/Homepage.tsx": () => import("../components/mockups/bis-homepage/Homepage.tsx")
};
